# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - RegNxtBIRDPortalD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Print env variables (USE WITH CAUTION)
        run: |
          echo "VITE_API_BASE_URL=${VITE_API_BASE_URL}"
          echo "VITE_FAST_API_BACKEND=${VITE_FAST_API_BACKEND}"

      - name: Check .env file
        run: |
          if grep -q VITE_API_BASE_URL .env && grep -q VITE_FAST_API_BACKEND .env; then
            echo "Both environment variables are present in .env file"
          else
            echo "One or both environment variables are missing from .env file"
            exit 1
          fi
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_42208F8AE7C44E20B2CD2C6B9F484042 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_292D92A9B52246B1B4D4A97BFA110129 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F203A333E2F646A58E77844B66E299EF }}

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "RegNxtBIRDPortalD"
          slot-name: "Production"
          package: .
